### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by shah1994** [grandeurtech/grandeurcloud-arduino-sdk#17]
I have tried compiling the code and it gives following error. 
PS: I have installed the libraries as instructed in the email. 

Arduino: 1.6.5 (Windows 8.1), Board: "LOLIN(WEMOS) D1 mini Pro, 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), 16M (14M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

C:\Users\Hasnain\Documents\Arduino\libraries\grandeurcloud-arduino-sdk-master\src\Duplex.cpp:26:18: fatal error: Hash.h: No such file or directory
 #include <Hash.h>
                  ^
compilation terminated.
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by moizhusnain** [comment]
Wow. Great issue.
