### ISSUE TITLE
Device connection listener

### ISSUE THREAD

**Issue by moizhusnain** [grandeurtech/grandeurcloud-arduino-sdk#8]
We have added two connection listeners i.e. Apollo Connection Listener, Apollo Disconnection Listener which isn't consistent with the JS SDK where there is a single listener called onConnection. So whenever state gets a change, we send `CONNECTED` or `DISCONNECTED` in the callback argument. 
Secondly, this should be extended to send other events like related to WiFi.

**Comment by abdullahmahboob** [comment]
This can be done. But in my opinion, we should separate WiFi event handler from Apollo event handler. That way, Apollo event handler will completely imitate the one in JS SDK and we can refer to WiFi event handler as a separate device-specific events handler.

**Comment by moizhusnain** [comment]
That't a great idea. Then let's add two event handlers `onConnection` and `onWifi`
Plus wanted to ask about the getter functions. There are so many functions to get wifi information and stuff. Since we are using JSON everywhere, why don't we create a single function `getConfig` which will return all the information in JSON object format. Then we can also add a function `setConfig` in future.

**Comment by abdullahmahboob** [comment]
Looks nice to me. I'll do it.

**Comment by abdullahmahboob** [comment]
Both are implemented.
